### ISSUE TITLE
Encoder Clear Handler

### ISSUE THREAD

**Issue by art725** [PacktPublishing/Learn-Robotics-Programming-Second-Edition#3]
https://github.com/PacktPublishing/Learn-Robotics-Programming-Second-Edition/blob/33fffd902923ab195c124326a19b821daf525bff/chapter11/robot.py#L72

Hi Danny,
Shouldn't these handlers reference the .reset instead of the .stop?

**Comment by dannystaple** [comment]
We definitely want to close the device (which stop does in the underlying code). Perhaps stop_all should be "tear_down" as it not only stops everything but intentionally tears down device handlers so they don't keep making calls. 

Reset will only set the counter back to 0 to carry on counting again.
