### ISSUE TITLE
Default user needs to be set up when creating the imager

### ISSUE THREAD

**Issue by SubaruSpirit** [PacktPublishing/Learn-Robotics-Programming-Second-Edition#6]
An recent update to Raspberry Pi OS has removed the default user of pi and password being raspberry. Instead, it should be set up when creating the boot imager: https://www.raspberrypi.com/news/raspberry-pi-bullseye-update-april-2022/

You can add some explanations in Chapter 3 under preparing sd card. After choosing OS, and choosing an sd card, instead of clicking `write` straight away, user should click settings to set up a user. Although there is a way to set up an user in the boot folder after the imager is written, it's easier to do it in the set up stage.

Without doing the aforementioned step, when user tries to do your Chapter 5 log in, access will be denied, because no default user exists. Thanks.

**Comment by dannystaple** [comment]
Thank you very much for this. Bullseye has made a number of changes that will not work well with this book, including the camera changes. For now I recommend staying with Buster https://www.raspberrypi.com/software/operating-systems/.

**Comment by dannystaple** [comment]
An updated edition, based on the new versions of the OS (among other things) is planned.

**Comment by SubaruSpirit** [comment]
Thanks for answering, looking forward to your new book! The problem is it can never catch up to the software update unfortunately. But as I have some programming background, will push through with the latest OS, I suppose it's fairly easy to figure it out with the camera changes?

**Comment by dannystaple** [comment]
My understanding is that the Picamera library that the current books camera through to web app and OpenGL stacks use is no longer available. Pushing through will need reintegrating onto Picamera2, assuming it will produce the sequence of frames in a similar way. An alternative is to look at OpenCV V4l integration, if the new camera uses v4l, then OpenCV V4L support might be the way forward. https://www.arducam.com/faq/opencv-v4l2-python-rpi/ may help. I am yet to research this one.

**Comment by dannystaple** [comment]
Hello, I've created a discord server for readers of my books to talk with me and other robot builders at https://discord.gg/4kcSNf4Npp. It's a bit quiet yet, but it would be great if you come to join us.
